pipeline {
  agent any
  stages {
    stage('检出') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: env.GIT_BUILD_REF]],
          userRemoteConfigs: [[
            url: env.GIT_REPO_URL,
            credentialsId: env.CREDENTIALS_ID
          ]]])
        }
      }
      stage('升级环境') {
        steps {
          sh '''
              sudo apt install nasm
              nasm -version
              wget "https://www.zlib.net/fossils/zlib-1.2.9.tar.gz"
              tar -zxvf zlib-1.2.9.tar.gz
              cd zlib-1.2.9
              ./configure
              make -j8
              make install
              '''
        }
      }
      stage('安装依赖') {
        steps {
          sh 'npm install'
        }
      }
      stage('编译') {
        steps {
          sh 'npm run build'
        }
      }
      stage('上传到 COS Bucket') {
        steps {
          useCustomStepPlugin(key: 'coding-public:cos_upload', version: 'latest', params: [secret_id:'{{secretId}}',secret_key:'{{secretKey}}',bucket:'{{bucket}}',region:'{{region}}',remote:'/{{projectName}}',local:'$WORKSPACE/dist'])
          echo "上传成功，访问 {{domain}}/{{projectName}}/index.html 预览效果"
        }
      }
    }
  }